### ISSUE TITLE
gem install rcov

### ISSUE THREAD

**Issue by denegny** [blaine/xmpp4r-simple#14]
ruby 2.3.1

``` bash
gem install rcov

Building native extensions.  This could take a while...
ERROR:  Error installing rcov:
    ERROR: Failed to build gem native extension.

compiling 1.8/callsite.c
1.8/callsite.c:2:17: fatal error: env.h:
```

**Comment by ElminDmitry** [comment]
I have the same issue

**Comment by nazmifr** [comment]
I think I'm having the same problem than both of you when I try to install xmpp4r-simple 0.8.7 with ruby 2.1 on GNU/Linux Devuan (and the 0.8.8 version has a bug so I can't use it :/ ). It seems that Rcov doesn't work with Ruby >1.8, the thing is that it seems to be in the makefile that rcov is used, which makes it difficult to replace for noobs like me and probably others.
According to a contributor on the rcov github page:
https://github.com/relevance/rcov/issues/84
"1.9+ support has been completely removed. If you are on 1.9 or higher, you should be using simplecov"
